name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
    runs-on: ubuntu-latest
    env:
      UPSTREAM_WORKSPACE: upstream.repos
      AFTER_SETUP_UPSTREAM_WORKSPACE: sudo apt update && sudo apt install -y libcurl4-openssl-dev nlohmann-json3-dev libb64-dev
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
